# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: new/constraints.xdc

# Block Designs: bd/design_1/design_1.bd
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1 || ORIG_REF_NAME==design_1} -quiet] -quiet

# IP: bd/design_1/ip/design_1_processing_system7_0_0/design_1_processing_system7_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_processing_system7_0_0 || ORIG_REF_NAME==design_1_processing_system7_0_0} -quiet] -quiet

# IP: bd/design_1/ip/design_1_hdmi_tx_0_0_2/design_1_hdmi_tx_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_hdmi_tx_0_0 || ORIG_REF_NAME==design_1_hdmi_tx_0_0} -quiet] -quiet

# IP: bd/design_1/ip/design_1_clk_wiz_0_0_2/design_1_clk_wiz_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_clk_wiz_0_0 || ORIG_REF_NAME==design_1_clk_wiz_0_0} -quiet] -quiet

# IP: bd/design_1/ip/design_1_vga_controller_0_0/design_1_vga_controller_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_vga_controller_0_0 || ORIG_REF_NAME==design_1_vga_controller_0_0} -quiet] -quiet

# IP: bd/design_1/ip/design_1_game_logic_0_0/design_1_game_logic_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_game_logic_0_0 || ORIG_REF_NAME==design_1_game_logic_0_0} -quiet] -quiet

# IP: bd/design_1/ip/design_1_game_clock_0_0/design_1_game_clock_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_game_clock_0_0 || ORIG_REF_NAME==design_1_game_clock_0_0} -quiet] -quiet

# XDC: /home/timon/Documents/vivado_snake/project_final2.gen/sources_1/bd/design_1/design_1_ooc.xdc
